# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    myco_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

myco_arm_controller:
  ros__parameters:
    joints:
      - myco_joint1
      - myco_joint2
      - myco_joint3
      - myco_joint4
      - myco_joint5
      - myco_joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity